# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mcp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcp.proto\x12\x03mcp\"_\n\x19GetAnalysisContextRequest\x12\x18\n\x10pull_request_url\x18\x01 \x01(\t\x12\x15\n\rrepository_id\x18\x02 \x01(\t\x12\x11\n\tcommit_id\x18\x03 \x01(\t\":\n\x0f\x41nalysisContext\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\t\"R\n\x17\x41nalysisContextResponse\x12&\n\x08\x63ontexts\x18\x01 \x03(\x0b\x32\x14.mcp.AnalysisContext\x12\x0f\n\x07message\x18\x02 \x01(\t2`\n\nMcpService\x12R\n\x12GetAnalysisContext\x12\x1e.mcp.GetAnalysisContextRequest\x1a\x1c.mcp.AnalysisContextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETANALYSISCONTEXTREQUEST']._serialized_start=18
  _globals['_GETANALYSISCONTEXTREQUEST']._serialized_end=113
  _globals['_ANALYSISCONTEXT']._serialized_start=115
  _globals['_ANALYSISCONTEXT']._serialized_end=173
  _globals['_ANALYSISCONTEXTRESPONSE']._serialized_start=175
  _globals['_ANALYSISCONTEXTRESPONSE']._serialized_end=257
  _globals['_MCPSERVICE']._serialized_start=259
  _globals['_MCPSERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
