#!/usr/bin/env bash
set -euo pipefail

TARGET_REPO="${TARGET_REPO:-}"
BASE_BRANCH="${BASE_BRANCH:-main}"
BRANCH_PREFIX="${BRANCH_PREFIX:-mitig8it/live-suggestion-validation}"
APP_SLUG="${APP_SLUG:-mitig8it}"
POLL_SECONDS="${POLL_SECONDS:-15}"
MAX_POLLS="${MAX_POLLS:-20}"
API_URL="${API_URL:-}"
ANALYSIS_URL="${ANALYSIS_URL:-}"
TMP_ROOT="${TMPDIR:-/tmp}"

if [[ -z "$TARGET_REPO" ]]; then
  echo "TARGET_REPO is required, for example: TARGET_REPO=owner/repo $0"
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI (gh) is required."
  exit 1
fi

if [[ -n "$API_URL" ]]; then
  echo "[preflight] Checking API health at $API_URL/health"
  curl -fsS "$API_URL/health" >/dev/null
fi

if [[ -n "$ANALYSIS_URL" ]]; then
  echo "[preflight] Checking analysis health at $ANALYSIS_URL/health"
  curl -fsS "$ANALYSIS_URL/health" >/dev/null
fi

timestamp="$(date +%Y%m%d-%H%M%S)"
branch_name="${BRANCH_PREFIX}-${timestamp}"
workdir="$(mktemp -d "$TMP_ROOT/mitig8it-live-validation.XXXXXX")"
repo_dir="$workdir/repo"
pr_url=""

cleanup() {
  if [[ -n "$pr_url" ]]; then
    echo "[info] Validation PR: $pr_url"
  fi
  echo "[info] Temporary checkout preserved at: $repo_dir"
}
trap cleanup EXIT

echo "[1/7] Cloning $TARGET_REPO into $repo_dir"
gh repo clone "$TARGET_REPO" "$repo_dir" -- --quiet

cd "$repo_dir"

echo "[2/7] Creating branch $branch_name from $BASE_BRANCH"
git fetch origin "$BASE_BRANCH" --quiet
git checkout "$BASE_BRANCH" --quiet
git pull --ff-only origin "$BASE_BRANCH" --quiet
git checkout -b "$branch_name" --quiet

fixture_dir="mitig8it_live_validation"
mkdir -p "$fixture_dir"

cat > "$fixture_dir/secret.js" <<'EOF'
const apiKey = "sk_live_1234567890abcdef";
module.exports = { apiKey };
EOF

cat > "$fixture_dir/sql.js" <<'EOF'
function loadUser(db, userId) {
  return db.query("SELECT * FROM users WHERE id = " + userId);
}
EOF

cat > "$fixture_dir/README.md" <<'EOF'
# Mitig8it Live Validation Fixture

This directory is generated by the live suggestion validation harness.
It intentionally contains obvious vulnerable samples for PR review testing.
EOF

echo "[3/7] Committing validation fixture"
git add "$fixture_dir"
git commit -m "Chore: add live suggestion validation fixture" --quiet

echo "[4/7] Pushing branch"
git push -u origin "$branch_name" --quiet

echo "[5/7] Opening PR"
pr_url="$(gh pr create \
  --base "$BASE_BRANCH" \
  --head "$branch_name" \
  --title "Chore: live suggestion validation fixture" \
  --body "## Purpose
- trigger Mitig8it against obvious secret and SQL concat findings
- validate that PR review output includes suggestion-based fixes

## Fixture
- \`$fixture_dir/secret.js\`
- \`$fixture_dir/sql.js\`

## Cleanup
- close this PR after validation
- delete branch \`$branch_name\` after use" \
)"

pr_number="$(gh pr view "$pr_url" --json number --jq '.number')"
echo "Created PR #$pr_number: $pr_url"

repo_api="repos/$TARGET_REPO/pulls/$pr_number"

echo "[6/7] Polling GitHub for Mitig8it review output"
review_found=0
suggestion_found=0
for ((attempt = 1; attempt <= MAX_POLLS; attempt += 1)); do
  review_body="$(
    gh api "$repo_api/reviews" \
      --jq '.[] | select(.body != null and (.body | contains("<!-- mitig8it-review -->"))) | .body' \
      2>/dev/null || true
  )"
  comment_body="$(
    gh api "$repo_api/comments" \
      --jq '.[] | select(.body != null and (.body | contains("```suggestion"))) | .body' \
      2>/dev/null || true
  )"

  if [[ -n "$review_body" ]]; then
    review_found=1
  fi
  if [[ -n "$comment_body" ]]; then
    suggestion_found=1
  fi

  if [[ "$review_found" -eq 1 && "$suggestion_found" -eq 1 ]]; then
    echo "[7/7] Success"
    echo "Mitig8it review summary detected."
    echo "Suggestion block detected in inline PR comments."
    exit 0
  fi

  echo "  poll $attempt/$MAX_POLLS: review=$review_found suggestion=$suggestion_found"
  sleep "$POLL_SECONDS"
done

echo "[7/7] Validation incomplete"
if [[ "$review_found" -eq 0 ]]; then
  echo "No Mitig8it review summary detected yet."
fi
if [[ "$suggestion_found" -eq 0 ]]; then
  echo "No inline suggestion block detected yet."
fi
echo "Inspect the PR manually: $pr_url"
exit 1
